import { Expense, Journey, Person } from '../types';
import { calculateJourneyBalance, getPersonExpensesSummary } from './calculations';

export interface ShareOptions {
  includeExpenses: boolean;
  includeBalances: boolean;
  includeSettlements: boolean;
  includeSummary: boolean;
}

export const formatJourneyForSharing = (
  journey: Journey,
  expenses: Expense[],
  options: ShareOptions = {
    includeExpenses: true,
    includeBalances: true,
    includeSettlements: true,
    includeSummary: true,
  }
): string => {
  const balance = calculateJourneyBalance(expenses, journey.participants);
  const lines: string[] = [];

  // Header
  lines.push(`🎒 ${journey.name}`);
  if (journey.description) {
    lines.push(`📝 ${journey.description}`);
  }
  lines.push('');

  // Summary
  if (options.includeSummary) {
    lines.push('📊 SUMMARY');
    lines.push('─'.repeat(20));
    lines.push(`💰 Total Expenses: $${balance.totalExpenses.toFixed(2)}`);
    lines.push(`📋 Number of Expenses: ${expenses.length}`);
    lines.push(`👥 Participants: ${journey.participants.length}`);
    lines.push(`📅 Created: ${new Date(journey.createdAt).toLocaleDateString()}`);
    lines.push('');
  }

  // Expenses List
  if (options.includeExpenses && expenses.length > 0) {
    lines.push('💸 EXPENSES');
    lines.push('─'.repeat(20));
    
    expenses.forEach((expense, index) => {
      const paidByName = getPersonName(expense.paidBy, journey.participants);
      const splitNames = expense.splitBetween
        .map(id => getPersonName(id, journey.participants))
        .join(', ');
      
      lines.push(`${index + 1}. ${expense.title}`);
      lines.push(`   💵 $${expense.amount.toFixed(2)}`);
      lines.push(`   👤 Paid by: ${paidByName}`);
      lines.push(`   🔄 Split: ${splitNames}`);
      lines.push(`   📅 ${new Date(expense.date).toLocaleDateString()}`);
      if (expense.description) {
        lines.push(`   📝 ${expense.description}`);
      }
      lines.push('');
    });
  }

  // Individual Balances
  if (options.includeBalances) {
    lines.push('⚖️ BALANCES');
    lines.push('─'.repeat(20));
    
    journey.participants.forEach(person => {
      const summary = getPersonExpensesSummary(expenses, person.id);
      const balanceAmount = balance.balances[person.id] || 0;
      
      lines.push(`👤 ${person.name}`);
      lines.push(`   💳 Paid: $${summary.totalPaid.toFixed(2)}`);
      lines.push(`   🧾 Share: $${summary.totalShare.toFixed(2)}`);
      
      if (balanceAmount > 0.01) {
        lines.push(`   🔴 Owes: $${balanceAmount.toFixed(2)}`);
      } else if (balanceAmount < -0.01) {
        lines.push(`   🟢 Owed: $${Math.abs(balanceAmount).toFixed(2)}`);
      } else {
        lines.push(`   ✅ All settled`);
      }
      lines.push('');
    });
  }

  // Settlement Suggestions
  if (options.includeSettlements && balance.settlements.length > 0) {
    lines.push('💸 SUGGESTED PAYMENTS');
    lines.push('─'.repeat(20));
    
    balance.settlements.forEach((settlement, index) => {
      const fromName = getPersonName(settlement.from, journey.participants);
      const toName = getPersonName(settlement.to, journey.participants);
      lines.push(`${index + 1}. ${fromName} → ${toName}: $${settlement.amount.toFixed(2)}`);
    });
    lines.push('');
  }

  // Footer
  lines.push('📱 Generated by Splitzter');
  lines.push(`🕐 ${new Date().toLocaleString()}`);

  return lines.join('\n');
};

export const formatExpenseListForSharing = (
  journey: Journey,
  expenses: Expense[]
): string => {
  const lines: string[] = [];

  lines.push(`📋 ${journey.name} - Expense List`);
  lines.push('');

  if (expenses.length === 0) {
    lines.push('No expenses recorded yet.');
    return lines.join('\n');
  }

  expenses.forEach((expense, index) => {
    const paidByName = getPersonName(expense.paidBy, journey.participants);
    const splitAmount = expense.amount / expense.splitBetween.length;
    
    lines.push(`${index + 1}. ${expense.title} - $${expense.amount.toFixed(2)}`);
    lines.push(`   Paid by ${paidByName}`);
    lines.push(`   $${splitAmount.toFixed(2)} per person`);
    lines.push('');
  });

  const totalAmount = expenses.reduce((sum, exp) => sum + exp.amount, 0);
  lines.push(`Total: $${totalAmount.toFixed(2)}`);

  return lines.join('\n');
};

export const formatSettlementsForSharing = (
  journey: Journey,
  expenses: Expense[]
): string => {
  const balance = calculateJourneyBalance(expenses, journey.participants);
  const lines: string[] = [];

  lines.push(`💰 ${journey.name} - Settlements`);
  lines.push('');

  if (balance.settlements.length === 0) {
    lines.push('🎉 Everyone is settled up!');
    return lines.join('\n');
  }

  lines.push('To settle all debts:');
  lines.push('');

  balance.settlements.forEach((settlement, index) => {
    const fromName = getPersonName(settlement.from, journey.participants);
    const toName = getPersonName(settlement.to, journey.participants);
    lines.push(`${index + 1}. ${fromName} pays ${toName} $${settlement.amount.toFixed(2)}`);
  });

  lines.push('');
  lines.push('After these payments, everyone will be even! ✅');

  return lines.join('\n');
};

export const formatPersonalSummaryForSharing = (
  journey: Journey,
  expenses: Expense[],
  personId: string
): string => {
  const person = journey.participants.find(p => p.id === personId);
  if (!person) return 'Person not found';

  const summary = getPersonExpensesSummary(expenses, personId);
  const balance = calculateJourneyBalance(expenses, journey.participants);
  const personalBalance = balance.balances[personId] || 0;

  const lines: string[] = [];

  lines.push(`👤 ${person.name}'s Summary`);
  lines.push(`🎒 Journey: ${journey.name}`);
  lines.push('');

  lines.push('💳 Your Payments:');
  const personalExpenses = expenses.filter(exp => exp.paidBy === personId);
  if (personalExpenses.length === 0) {
    lines.push('   No payments made');
  } else {
    personalExpenses.forEach(exp => {
      lines.push(`   • ${exp.title}: $${exp.amount.toFixed(2)}`);
    });
  }
  lines.push(`   Total Paid: $${summary.totalPaid.toFixed(2)}`);
  lines.push('');

  lines.push('🧾 Your Share:');
  lines.push(`   Total Share: $${summary.totalShare.toFixed(2)}`);
  lines.push('');

  lines.push('⚖️ Balance:');
  if (personalBalance > 0.01) {
    lines.push(`   🔴 You owe: $${personalBalance.toFixed(2)}`);
  } else if (personalBalance < -0.01) {
    lines.push(`   🟢 You are owed: $${Math.abs(personalBalance).toFixed(2)}`);
  } else {
    lines.push(`   ✅ You're all settled!`);
  }

  return lines.join('\n');
};

const getPersonName = (personId: string, participants: Person[]): string => {
  return participants.find(p => p.id === personId)?.name || 'Unknown';
};